
if (XII_3RDPARTY_SDL_SUPPORT)
  # Efforts to automatically mark as advanced did not cover all cases.
  mark_as_advanced(FORCE SDL_ALSA)
  mark_as_advanced(FORCE SDL_ALSA_SHARED)
  mark_as_advanced(FORCE SDL_ALTIVEC)
  mark_as_advanced(FORCE SDL_ARMNEON)
  mark_as_advanced(FORCE SDL_ARMSIMD)
  mark_as_advanced(FORCE SDL_ASAN)
  mark_as_advanced(FORCE SDL_ASSEMBLY)
  mark_as_advanced(FORCE SDL_ASSERTIONS)
  mark_as_advanced(FORCE SDL_AVX)
  mark_as_advanced(FORCE SDL_AVX2)
  mark_as_advanced(FORCE SDL_AVX512F)
  mark_as_advanced(FORCE SDL_BACKGROUNDING_SIGNAL)
  mark_as_advanced(FORCE SDL_CCACHE)
  mark_as_advanced(FORCE SDL_CLANG_TIDY)
  mark_as_advanced(FORCE SDL_CLOCK_GETTIME)
  mark_as_advanced(FORCE SDL_COCOA)
  mark_as_advanced(FORCE SDL_DBUS)
  mark_as_advanced(FORCE SDL_DIRECTX)
  mark_as_advanced(FORCE SDL_DISABLE_INSTALL)
  mark_as_advanced(FORCE SDL_DISABLE_UNINSTALL)
  mark_as_advanced(FORCE SDL_DISKAUDIO)
  mark_as_advanced(FORCE SDL_DUMMYAUDIO)
  mark_as_advanced(FORCE SDL_DUMMYCAMERA)
  mark_as_advanced(FORCE SDL_DUMMYVIDEO)
  mark_as_advanced(FORCE SDL_EXAMPLES)
  mark_as_advanced(FORCE SDL_EXAMPLES_LINK_SHARED)
  mark_as_advanced(FORCE SDL_FOREGROUNDING_SIGNAL)
  mark_as_advanced(FORCE SDL_GCC_ATOMICS)
  mark_as_advanced(FORCE SDL_GPU_DXVK)
  mark_as_advanced(FORCE SDL_HIDAPI)
  mark_as_advanced(FORCE SDL_HIDAPI_JOYSTICK)
  mark_as_advanced(FORCE SDL_HIDAPI_LIBUSB)
  mark_as_advanced(FORCE SDL_HIDAPI_LIBUSB_SHARED)
  mark_as_advanced(FORCE SDL_IBUS)
  mark_as_advanced(FORCE SDL_INSTALL_TESTS)
  mark_as_advanced(FORCE SDL_JACK)
  mark_as_advanced(FORCE SDL_JACK_SHARED)
  mark_as_advanced(FORCE SDL_KMSDRM)
  mark_as_advanced(FORCE SDL_KMSDRM_SHARED)
  mark_as_advanced(FORCE SDL_LASX)
  mark_as_advanced(FORCE SDL_LIBC)
  mark_as_advanced(FORCE SDL_LIBICONV)
  mark_as_advanced(FORCE SDL_LIBUDEV)
  mark_as_advanced(FORCE SDL_LIBURING)
  mark_as_advanced(FORCE SDL_LSX)
  mark_as_advanced(FORCE SDL_METAL)
  mark_as_advanced(FORCE SDL_MMX)
  mark_as_advanced(FORCE SDL_OFFSCREEN)
  mark_as_advanced(FORCE SDL_OPENGL)
  mark_as_advanced(FORCE SDL_OPENGLES)
  mark_as_advanced(FORCE SDL_OPENVR)
  mark_as_advanced(FORCE SDL_OSS)
  mark_as_advanced(FORCE SDL_PIPEWIRE)
  mark_as_advanced(FORCE SDL_PIPEWIRE_SHARED)
  mark_as_advanced(FORCE SDL_PTHREADS)
  mark_as_advanced(FORCE SDL_PTHREADS_SEM)
  mark_as_advanced(FORCE SDL_PULSEAUDIO)
  mark_as_advanced(FORCE SDL_PULSEAUDIO_SHARED)
  mark_as_advanced(FORCE SDL_RENDER_D3D)
  mark_as_advanced(FORCE SDL_RENDER_D3D11)
  mark_as_advanced(FORCE SDL_RENDER_D3D12)
  mark_as_advanced(FORCE SDL_RENDER_GPU)
  mark_as_advanced(FORCE SDL_RENDER_METAL)
  mark_as_advanced(FORCE SDL_RENDER_VULKAN)
  mark_as_advanced(FORCE SDL_ROCKCHIP)
  mark_as_advanced(FORCE SDL_RPATH)
  mark_as_advanced(FORCE SDL_RPI)
  mark_as_advanced(FORCE SDL_SNDIO)
  mark_as_advanced(FORCE SDL_SNDIO_SHARED)
  mark_as_advanced(FORCE SDL_SSE)
  mark_as_advanced(FORCE SDL_SSE2)
  mark_as_advanced(FORCE SDL_SSE3)
  mark_as_advanced(FORCE SDL_SSE4_1)
  mark_as_advanced(FORCE SDL_SSE4_2)
  mark_as_advanced(FORCE SDL_SYSTEM_ICONV)
  mark_as_advanced(FORCE SDL_TESTS)
  mark_as_advanced(FORCE SDL_TESTS_LINK_SHARED)
  mark_as_advanced(FORCE SDL_VIRTUAL_JOYSTICK)
  mark_as_advanced(FORCE SDL_VIVANTE)
  mark_as_advanced(FORCE SDL_VULKAN)
  mark_as_advanced(FORCE SDL_WASAPI)
  mark_as_advanced(FORCE SDL_WAYLAND)
  mark_as_advanced(FORCE SDL_WAYLAND_LIBDECOR)
  mark_as_advanced(FORCE SDL_WAYLAND_LIBDECOR_SHARED)
  mark_as_advanced(FORCE SDL_WAYLAND_SHARED)
  mark_as_advanced(FORCE SDL_X11)
  mark_as_advanced(FORCE SDL_X11_SHARED)
  mark_as_advanced(FORCE SDL_X11_XCURSOR)
  mark_as_advanced(FORCE SDL_X11_XDBE)
  mark_as_advanced(FORCE SDL_X11_XFIXES)
  mark_as_advanced(FORCE SDL_X11_XINPUT)
  mark_as_advanced(FORCE SDL_X11_XRANDR)
  mark_as_advanced(FORCE SDL_X11_XSCRNSAVER)
  mark_as_advanced(FORCE SDL_X11_XSHAPE)
  mark_as_advanced(FORCE SDL_X11_XSYNC)
  mark_as_advanced(FORCE SDL_XINPUT)

  mark_as_advanced(FORCE SDL_AUDIO)
  mark_as_advanced(FORCE SDL_CAMERA)
  mark_as_advanced(FORCE SDL_CPU_ARM32)
  mark_as_advanced(FORCE SDL_CPU_ARM64)
  mark_as_advanced(FORCE SDL_CPU_ARM64EC)
  mark_as_advanced(FORCE SDL_CPU_EMSCRIPTEN)
  mark_as_advanced(FORCE SDL_CPU_LOONGARCH64)
  mark_as_advanced(FORCE SDL_CPU_POWERPC64)
  mark_as_advanced(FORCE SDL_CPU_POWERPC32)
  mark_as_advanced(FORCE SDL_CPU_X64)
  mark_as_advanced(FORCE SDL_CPU_X86)
  mark_as_advanced(FORCE SDL_DIALOG)
  mark_as_advanced(FORCE SDL_GPU)
  mark_as_advanced(FORCE SDL_HAPTIC)
  mark_as_advanced(FORCE SDL_INSTALL_CMAKEDIR_ROOT)
  mark_as_advanced(FORCE SDL_JOYSTICK)
  mark_as_advanced(FORCE SDL_POWER)
  mark_as_advanced(FORCE SDL_PRESEED)
  mark_as_advanced(FORCE SDL_RENDER)
  mark_as_advanced(FORCE SDL_REVISION)
  mark_as_advanced(FORCE SDL_SENSOR)
  mark_as_advanced(FORCE SDL_SHARED)
  mark_as_advanced(FORCE SDL_STATIC)
  mark_as_advanced(FORCE SDL_TESTS_TIMEOUT_MULTIPLIER)
  mark_as_advanced(FORCE SDL_TEST_LIBRARY)
  mark_as_advanced(FORCE SDL_VENDOR_INFO)
  mark_as_advanced(FORCE SDL_VIDEO)
  mark_as_advanced(FORCE SDL_WERROR)

  mark_as_advanced(FORCE LibUSB_COMPILE_OPTIONS)
  mark_as_advanced(FORCE LibUSB_INCLUDE_PATH)
  mark_as_advanced(FORCE LibUSB_LIBRARY)
  mark_as_advanced(FORCE LibUSB_LINK_FLAGS)
  mark_as_advanced(FORCE LibUSB_LINK_LIBRARIES)

  if(TARGET SDL_uclibc)

    set_property(GLOBAL APPEND PROPERTY "EXPORT_PROJECTS" SDL_uclibc)

    xii_set_project_ide_folder(SDL_uclibc "Source/ThirdParty/SDL")

    xii_set_target_output_dirs(SDL_uclibc ${XII_OUTPUT_DIRECTORY_LIB} ${XII_OUTPUT_DIRECTORY_DLL})

  endif()

  if(TARGET SDL3-shared)

    set_property(GLOBAL APPEND PROPERTY "EXPORT_PROJECTS" SDL3-shared)

    xii_set_project_ide_folder(SDL3-shared "Source/ThirdParty/SDL")

    xii_set_target_output_dirs(SDL3-shared ${XII_OUTPUT_DIRECTORY_LIB} ${XII_OUTPUT_DIRECTORY_DLL})

  endif()

  if(TARGET SDL3-static)

    set_property(GLOBAL APPEND PROPERTY "EXPORT_PROJECTS" SDL3-static)

    xii_set_project_ide_folder(SDL3-static "Source/ThirdParty/SDL")

    xii_set_target_output_dirs(SDL3-static ${XII_OUTPUT_DIRECTORY_LIB} ${XII_OUTPUT_DIRECTORY_DLL})

  endif()
endif()